# /etc/wireplumber/wireplumber.conf.d/50-disable-suspend.conf
# Prevent ALSA node suspension on idle to eliminate popping on SSM4567 / NAU8825 (Chell AVS)
monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.*"
      }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
      }
    }
  }
]
